version: "3.3"

services:
  web:
    image: fronron/odoo_15_release_20220523:1.0
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
#    command: --
#    environment:
#      HOST: db
#      USER: odoo
#      PASSWORD: myodoo
    volumes:
      - ./config:/etc/odoo
      - ./odoo-web-data:/var/lib/odoo
      - ./htm_addons/.:/mnt/extra-addons
#      - ./enterprise:/mnt/enterprise
    restart: always

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
volumes:
#  odoo-web-data:
  odoo-db-data: